<Project>
  <PropertyGroup Condition="'$(OS)' == 'Windows_NT'">
    <AloeInstallRoot Condition="'$(AloeInstallRoot)' == ''">E:\Aloe</AloeInstallRoot>
    <OutputPath>$(AloeInstallRoot)\bin\</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
  </PropertyGroup>
</Project>
